export const GET_MAIN_CONTENT_PREVIEW = 'GET_MAIN_CONTENT_PREVIEW';
export const GET_ASK_CONTENT_PREVIEW = 'GET_ASK_CONTENT_PREVIEW';

export const GET_MAIN_CONTENT_DETAIL = 'GET_MAIN_CONTENT_DETAIL';
