export const GET_HOME_WRITE_PREVIEW = 'GET_HOME_WRITE_PREVIEW';
export const GET_HOME_LIKE_PREVIEW = 'GET_HOME_LIKE_PREVIEW';

export const GET_ASK_WRITE_PREVIEW = 'GET_ASK_WRITE_PREVIEW';
export const GET_ASK_LIKE_PREVIEW = 'GET_ASK_LIKE_PREVIEW';
